#!/bin/bash
PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Bar Appearance #####
# Configuring the general appearance of the bar.


sketchybar --bar position=top height=37 blur_radius=30 color=0xcc0d0d0d

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.

default=(
  padding_left=8
  padding_right=8
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=0xffe5e5e5
  label.color=0xffe5e5e5
  icon.padding_left=10
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=10
  background.drawing=off \
  background.corner_radius=6
  background.height=25
  animation.duration=0.3
  animation.easing="ease-in-out"
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####

SPACE_SIDS=(1 2 3 4 5 6 7 8 9 10)

for sid in "${SPACE_SIDS[@]}"
do
  sketchybar --add space space.$sid left \
             --set space.$sid space=$sid \
                              icon=$sid \
                              background.color=0xff2b2e33 \
                              background.corner_radius=6 \
                              background.height=25 \
                              label.font="sketchybar-app-font:Regular:16.0" \
                              label.padding_right=20 \
                              label.y_offset=-1 \
                              icon.color=0xff00ffff \
                              label.color=0xffff2eff \
                              script="$PLUGIN_DIR/space.sh"
done

sketchybar --add item space_separator left \
           --set space_separator icon="􀆊" \
                                 icon.padding_left=4 \
                                 label.drawing=off \
                                 background.drawing=off \
                                 icon.color=0xff00ffff \
                                 script="$PLUGIN_DIR/space_windows.sh" \
           --subscribe space_separator space_windows_change \
           --add item front_app left \
           --set front_app icon.drawing=on \
                          icon.font="sketchybar-app-font:Regular:16.0" \
                          icon.color=0xffff2eff \
                          background.drawing=off \
                          script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched \

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.

sketchybar \
  --add item clock right \
  --set clock update_freq=10 icon= script="$PLUGIN_DIR/clock.sh" \
                 icon.color=0xff00ffff \
  --add item volume right \
  --set volume script="$PLUGIN_DIR/volume.sh" \
                 icon.color=0xff00ffff \
  --subscribe volume volume_change \
  --add item battery right \
  --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
                 icon.color=0xfff9ff00 \
  --subscribe battery system_woke power_source_change \
  --add item cpu right \
  --set cpu update_freq=10 icon= script="$PLUGIN_DIR/cpu.sh" \
                 icon.color=0xff00ffff \
                 label.drawing=on \
  --add item media left \
           --set media script="$PLUGIN_DIR/media.sh" \
                       label.max_chars=23 \
                       icon.padding_left=0 \
                       scroll_texts=on \
                       icon=  \
                       icon.color=0xff00ffff  \
                       label.color=0xffe5e5e5  \
                       background.drawing=off \
                       update_freq=5\
  --add item logo right \
           --set logo icon="󰊤" \
                      label="jozefhdez" \
                      label.drawing=on \
                      icon.color=0xffff2eff  \
                      script="echo 'Loading'" \
                      click_script="open https://github.com/jozefhdez" \
                      icon.highlight_color=0xfff9ff00 \
                      icon.highlight=on \


##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update