#!/bin/bash

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
source "$CONFIG_DIR/colors.sh"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=37 blur_radius=30 color=0x40000000

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=8
  padding_right=8
  icon.font="Hack Nerd Font:Bold:17.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=0xffebdbb2
  label.color=0xffebdbb2
  icon.padding_left=10
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=10
  background.color=0xff282828
  background.corner_radius=6
  background.height=25
  animation.duration=0.3
  animation.easing="ease-in-out"
)
sketchybar --default "${default[@]}"

##### Adding Mission Control Space Indicators #####
# Let's add some mission control spaces:
# https://felixkratz.github.io/SketchyBar/config/components#space----associate-mission-control-spaces-with-an-item
# to indicate active and available mission control spaces.

SPACE_SIDS=(1 2 3 4 5 6 7 8 9 10)

for sid in "${SPACE_SIDS[@]}"
do
  sketchybar --add space space.$sid left                                 \
             --set space.$sid space=$sid                                 \
                              icon=$sid                                  \
                              background.color=0xff282828 \
                              background.corner_radius=6 \
                              background.height=25 \
                              label.font="sketchybar-app-font:Regular:16.0" \
                              label.padding_right=20                     \
                              label.y_offset=-1                          \
                              script="$PLUGIN_DIR/space.sh"
done

sketchybar --add item space_separator left                             \
           --set space_separator icon="􀆊"                                \
                                 icon.padding_left=4                   \
                                 label.drawing=off                     \
                                 background.drawing=off                \
                                 script="$PLUGIN_DIR/space_windows.sh" \
           --subscribe space_separator space_windows_change

##### Adding Left Items #####
# We add some regular items to the left side of the bar, where
# only the properties deviating from the current defaults need to be set

sketchybar --add item front_app left \
           --set front_app icon.drawing=on \
                          icon.font="sketchybar-app-font:Regular:16.0" \
                          script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched \

##### Adding Right Items #####
# In the same way as the left items we can add items to the right side.
# Additional position (e.g. center) are available, see:
# https://felixkratz.github.io/SketchyBar/config/items#adding-items-to-sketchybar

# Some items refresh on a fixed cycle, e.g. the clock runs its script once
# every 10s. Other items respond to events they subscribe to, e.g. the
# volume.sh script is only executed once an actual change in system audio
# volume is registered. More info about the event system can be found here:
# https://felixkratz.github.io/SketchyBar/config/events

sketchybar \
  --add item clock right \
  --set clock update_freq=10 icon= script="$PLUGIN_DIR/clock.sh" \
  --add item volume right \
  --set volume script="$PLUGIN_DIR/volume.sh" \
  --subscribe volume volume_change \
  --add item battery right \
  --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change \
  --add item cpu right \
  --set cpu update_freq=10 icon= script="$PLUGIN_DIR/cpu.sh" \
  --add item media left \
           --set media script="$PLUGIN_DIR/media.sh" \
                       label.max_chars=23 \
                       icon.padding_left=0 \
                       scroll_texts=on \
                       icon=  \
                       icon.color=0xffb8bb26  \
                       label.color=0xffb8bb26  \
                       background.drawing=off \
                       update_freq=5



sketchybar --add item logo right \
           --set logo icon="󰊤" \
                      label="JozefHdez" \
                      label.drawing=on \
                      icon.font="Hack Nerd Font:Bold:20.0" \
                      label.font="Hack Nerd Font:Bold:14.0" \
                      icon.color=0xff83a598  \
                      background.corner_radius=6 \
                      background.height=25 \
                      script="echo 'Logo cargado'" \
                      click_script="open https://github.com/jozefhdez" \
                      icon.highlight_color=0xff83a598 \
                      icon.highlight=on

sketchybar --add item settings right \
           --set settings icon="" \
                          icon.font="Hack Nerd Font:Bold:18.0" \
                          label="Setup" \
                          click_script="open -a 'System Settings'"

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update